apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      app: jupyter
      hasuraService: custom
    name: jupyter
    namespace: '{{ cluster.metadata.namespaces.user }}'
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: jupyter
      spec:
        containers:
        - image: hasura/base-git-image:0.7
          imagePullPolicy: IfNotPresent
          name: jupyter
          ports:
          - containerPort: 8888
            protocol: TCP
          resources: {}
          volumeMounts:
          - mountPath: /home/jovyan/work
            name: user-pv
          env:
          - name: GRANT_SUDO
            value: "yes"
        securityContext: {}
        terminationGracePeriodSeconds: 0
        volumes:
        - hostPath:
            path: /data/default/user
          name: user-pv
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: jupyter
      hasuraService: custom
    name: jupyter
    namespace: '{{ cluster.metadata.namespaces.user }}'
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8888
    selector:
      app: jupyter
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata: {}
